[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "JuPyMake"
version = "0.8"
description = "A simple interface to Polymake"
authors = [{name = "Sebastian Gutsche", email = "sebastian.gutsche@gmail.com"}]
urls = {Homepage = "https://github.com/sebasguts/JuPyMake"}
readme = "README.md"

[tool.setuptools]
license-files = ["COPYING", "GPLv2"]
